use SMV_UNIVER;
--№1
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM inner join AUDITORIUM_TYPE
on AUDITORIUM.[AUDITORIUM_TYPE] = AUDITORIUM_TYPE.AUDITORIUM_TYPE
--№2
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM inner join AUDITORIUM_TYPE
on AUDITORIUM.[AUDITORIUM_TYPE] = AUDITORIUM_TYPE.AUDITORIUM_TYPE and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'
--№3-1
select T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME
from AUDITORIUM as T1, AUDITORIUM_TYPE as T2
where T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE
--№3-2
select T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME
from AUDITORIUM as T1, AUDITORIUM_TYPE as T2
where T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE and T2.AUDITORIUM_TYPENAME like '%компьютер%'
--№4
select FACULTY.FACULTY_NAME as [факультет], 
	PULPIT.PULPIT_NAME as [кафедра], 
	PROFESSION.PROFESSION_NAME as [специальность], 
	GROUPS.IDGROUP as [группа], 
	SUBJECT.SUBJECT_NAME as [дисциплина], 
	STUDENT.NAME as [студент], 
	case
	when (PROGRESS.NOTE like 6) then 'шесть'
	when (PROGRESS.NOTE like 7) then 'семь'
	when (PROGRESS.NOTE like 8) then 'восемь'
	end [оценка]
from FACULTY ,
	 PULPIT ,
	 PROFESSION ,
	 GROUPS ,
	 SUBJECT ,
	 STUDENT ,
	 PROGRESS 
where PROGRESS.NOTE between 6 and 8 
	and SUBJECT.SUBJECT = PROGRESS.SUBJECT
	and PULPIT.PULPIT = SUBJECT.PULPIT
	and	STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT and
		GROUPS.IDGROUP = STUDENT.IDGROUP and
		PROFESSION.PROFESSION = GROUPS.PROFESSION and
		FACULTY.FACULTY = PROFESSION.FACULTY  
order by PROGRESS.NOTE desc
--№5
select FACULTY.FACULTY_NAME as [факультет], 
	PULPIT.PULPIT_NAME as [кафедра], 
	PROFESSION.PROFESSION_NAME as [специальность], 
	GROUPS.IDGROUP as [группа], 
	SUBJECT.SUBJECT_NAME as [дисциплина], 
	STUDENT.NAME as [студент], 
	case
	when (PROGRESS.NOTE like 6) then 'шесть'
	when (PROGRESS.NOTE like 7) then 'семь'
	when (PROGRESS.NOTE like 8) then 'восемь'
	end [оценка]
from FACULTY ,
	 PULPIT ,
	 PROFESSION ,
	 GROUPS ,
	 SUBJECT ,
	 STUDENT ,
	 PROGRESS 
where PROGRESS.NOTE between 6 and 8 
	and SUBJECT.SUBJECT = PROGRESS.SUBJECT
	and PULPIT.PULPIT = SUBJECT.PULPIT
	and	STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT and
		GROUPS.IDGROUP = STUDENT.IDGROUP and
		PROFESSION.PROFESSION = GROUPS.PROFESSION and
		FACULTY.FACULTY = PROFESSION.FACULTY  
order by
(
case
	when (PROGRESS.NOTE like 7) then 1
	when (PROGRESS.NOTE like 8) then 2
	else 3
end
)
--№6
select PULPIT.PULPIT_NAME as [Кафедра], isnull(TEACHER.TEACHER_NAME, '***') as [Преподаватель]
from PULPIT left outer join TEACHER
on TEACHER.PULPIT = PULPIT.PULPIT
--№7
select PULPIT.PULPIT_NAME as [Кафедра], isnull(TEACHER.TEACHER_NAME, '***') as [Преподаватель]
from TEACHER right outer join PULPIT 
on TEACHER.PULPIT = PULPIT.PULPIT
--№8
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM full outer join AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
--№9
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM cross join AUDITORIUM_TYPE
where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
----
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM inner join AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE